version: '3.8'
services:
  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
